name: Bazel Test Template

on:
  workflow_call:
    inputs:
      test_target:
        required: true
        type: string
        description: "The bazel target string this test invokes (e.g. //...)"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          # Scoping the disk cache by the test target helps prevent cache conflicts
          disk-cache: ${{ github.workflow }}-${{ inputs.test_target }}
          repository-cache: true

      - name: Run Bazel Target
        run: bazel test -c opt ${{ inputs.test_target }} --test_output=errors
