name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  host-tests:
    uses: ./.github/workflows/bazel_test_template.yaml
    with:
      test_target: '//...'
  lint:
    uses: ./.github/workflows/bazel_run_template.yaml
    with:
      target: ':lint' 
      args: "--check"
